# Developed By Oliver M
# Edited By Dawid S
from tkinter import *
from tkinter import ttk

window = Tk()
window.resizable(width=False, height=False)
window.title('Logic Gates Of Woe')

F1 = Frame(window)
F1.pack(fill = BOTH)
NB = ttk.Notebook(F1)
T1 = ttk.Frame(NB)
T2 = ttk.Frame(NB)
T3 = ttk.Frame(NB)
T4 = ttk.Frame(NB)
T5 = ttk.Frame(NB)
T6 = ttk.Frame(NB)
T7 = ttk.Frame(NB)

# AND TAB

ANDVar1 = IntVar(value = 0)
ANDVar2 = IntVar(value = 0)
ANDVar3 = IntVar(value = 0)
ANDVar4 = IntVar(value = 0)
ANDVar5 = IntVar(value = 0)
ANDVar6 = IntVar(value = 0)

Photo1 = PhotoImage(file = 'AND.gif')

L1 = ttk.Label(T1, text = '1')
L1.grid(row = 1, column = 1, padx = 10)
L2 = ttk.Label(T1, text = '1')
L2.grid(row = 1, column = 2, padx = 10)
R1 = ttk.Checkbutton(T1, variable = ANDVar1)
R1.grid(row = 1, column = 3)
L3 = ttk.Label(T1, text = '1')
L3.grid(row = 2, column = 1, padx = 10)
L4 = ttk.Label(T1, text = '0')
L4.grid(row = 2, column = 2, padx = 10)
R2 = ttk.Checkbutton(T1, variable = ANDVar2)
R2.grid(row = 2, column = 3)
L5 = ttk.Label(T1, text = '0')
L5.grid(row = 3, column = 1, padx = 10)
L6 = ttk.Label(T1, text = '1')
L6.grid(row = 3, column = 2, padx = 10)
R3 = ttk.Checkbutton(T1, variable = ANDVar3)
R3.grid(row = 3, column = 3)
L7 = ttk.Label(T1, text = '1')
L7.grid(row = 4, column = 1, padx = 10)
L8 = ttk.Label(T1, text = '1')
L8.grid(row = 4, column = 2, padx = 10)
R4 = ttk.Checkbutton(T1, variable = ANDVar4)
R4.grid(row = 4, column = 3)
B1 = ttk.Button(T1, text = 'Submit')
B1.grid(row = 1, column = 5, rowspan = 4)
P1 = Label(T1, image = Photo1)
P1.grid(row = 5, column = 2, rowspan = 4, columnspan = 4)
R5 = ttk.Checkbutton(T1, variable = ANDVar5)
R5.grid(row = 5, column = 1, rowspan = 2)
R6 = ttk.Checkbutton(T1, variable = ANDVar6)
R6.grid(row = 7, column = 1, rowspan = 2)
L9 = ttk.Label(T1, text = '0')
L9.grid(row = 5, column = 7, rowspan = 4)

# AND TAB
# NAND TAB

NANDVar1 = IntVar(value = 0)
NANDVar2 = IntVar(value = 0)
NANDVar3 = IntVar(value = 0)
NANDVar4 = IntVar(value = 0)
NANDVar5 = IntVar(value = 0)
NANDVar6 = IntVar(value = 0)

Photo2 = PhotoImage(file = 'NAND.gif')

L1 = ttk.Label(T2, text = '1')
L1.grid(row = 1, column = 1, padx = 10)
L2 = ttk.Label(T2, text = '1')
L2.grid(row = 1, column = 2, padx = 10)
R1 = ttk.Checkbutton(T2, variable = NANDVar1)
R1.grid(row = 1, column = 3)
L3 = ttk.Label(T2, text = '1')
L3.grid(row = 2, column = 1, padx = 10)
L4 = ttk.Label(T2, text = '0')
L4.grid(row = 2, column = 2, padx = 10)
R2 = ttk.Checkbutton(T2, variable = NANDVar2)
R2.grid(row = 2, column = 3)
L5 = ttk.Label(T2, text = '0')
L5.grid(row = 3, column = 1, padx = 10)
L6 = ttk.Label(T2, text = '1')
L6.grid(row = 3, column = 2, padx = 10)
R3 = ttk.Checkbutton(T2, variable = NANDVar3)
R3.grid(row = 3, column = 3)
L7 = ttk.Label(T2, text = '1')
L7.grid(row = 4, column = 1, padx = 10)
L8 = ttk.Label(T2, text = '1')
L8.grid(row = 4, column = 2, padx = 10)
R4 = ttk.Checkbutton(T2, variable = NANDVar4)
R4.grid(row = 4, column = 3)
B1 = ttk.Button(T2, text = 'Submit')
B1.grid(row = 1, column = 5, rowspan = 4)
P1 = Label(T2, image = Photo2)
P1.grid(row = 5, column = 2, rowspan = 4, columnspan = 4)
R5 = ttk.Checkbutton(T2, variable = NANDVar5)
R5.grid(row = 5, column = 1, rowspan = 2)
R6 = ttk.Checkbutton(T2, variable = NANDVar6)
R6.grid(row = 7, column = 1, rowspan = 2)
L9 = ttk.Label(T2, text = '0')
L9.grid(row = 5, column = 7, rowspan = 4)

# NAND TAB
# NOR TAB

NORVar1 = IntVar(value = 0)
NORVar2 = IntVar(value = 0)
NORVar3 = IntVar(value = 0)
NORVar4 = IntVar(value = 0)
NORVar5 = IntVar(value = 0)
NORVar6 = IntVar(value = 0)

Photo3 = PhotoImage(file = 'NOR.gif')

L1 = ttk.Label(T3, text = '1')
L1.grid(row = 1, column = 1, padx = 10)
L2 = ttk.Label(T3, text = '1')
L2.grid(row = 1, column = 2, padx = 10)
R1 = ttk.Checkbutton(T3, variable = NORVar1)
R1.grid(row = 1, column = 3)
L3 = ttk.Label(T3, text = '1')
L3.grid(row = 2, column = 1, padx = 10)
L4 = ttk.Label(T3, text = '0')
L4.grid(row = 2, column = 2, padx = 10)
R2 = ttk.Checkbutton(T3, variable = NORVar2)
R2.grid(row = 2, column = 3)
L5 = ttk.Label(T3, text = '0')
L5.grid(row = 3, column = 1, padx = 10)
L6 = ttk.Label(T3, text = '1')
L6.grid(row = 3, column = 2, padx = 10)
R3 = ttk.Checkbutton(T3, variable = NORVar3)
R3.grid(row = 3, column = 3)
L7 = ttk.Label(T3, text = '1')
L7.grid(row = 4, column = 1, padx = 10)
L8 = ttk.Label(T3, text = '1')
L8.grid(row = 4, column = 2, padx = 10)
R4 = ttk.Checkbutton(T3, variable = NORVar4)
R4.grid(row = 4, column = 3)
B1 = ttk.Button(T3, text = 'Submit')
B1.grid(row = 1, column = 5, rowspan = 4)
P1 = Label(T3, image = Photo3)
P1.grid(row = 5, column = 2, rowspan = 4, columnspan = 4)
R5 = ttk.Checkbutton(T3, variable = NORVar5)
R5.grid(row = 5, column = 1, rowspan = 2)
R6 = ttk.Checkbutton(T3, variable = NORVar6)
R6.grid(row = 7, column = 1, rowspan = 2)
L9 = ttk.Label(T3, text = '0')
L9.grid(row = 5, column = 7, rowspan = 4)

# NOR TAB
# NOT TAB

NOTVar1 = IntVar(value = 0)
NOTVar2 = IntVar(value = 0)
NOTVar3 = IntVar(value = 0)

Photo4 = PhotoImage(file = 'NOT.gif')

L1 = ttk.Label(T4, text = '1')
L1.grid(row = 1, column = 1, padx = 10)
R1 = ttk.Checkbutton(T4, variable = NOTVar1)
R1.grid(row = 1, column = 2)
L2 = ttk.Label(T4, text = '0')
L2.grid(row = 2, column = 1, padx = 10)
R2 = ttk.Checkbutton(T4, variable = NOTVar2)
R2.grid(row = 2, column = 2)
B1 = ttk.Button(T4, text = 'Submit')
B1.grid(row = 1, column = 3, rowspan = 2, columnspan = 4)
P1 = Label(T4, image = Photo4)
P1.grid(row = 3, column = 2, rowspan = 4, columnspan = 4)
R3 = ttk.Checkbutton(T4, variable = NOTVar3)
R3.grid(row = 3, column = 1, rowspan = 4)
L3 = ttk.Label(T4, text = '0')
L3.grid(row = 3, column = 7, rowspan = 4)

# NOT TAB
# OR TAB

ORVar1 = IntVar(value = 0)
ORVar2 = IntVar(value = 0)
ORVar3 = IntVar(value = 0)
ORVar4 = IntVar(value = 0)
ORVar5 = IntVar(value = 0)
ORVar6 = IntVar(value = 0)

Photo5 = PhotoImage(file = 'OR.gif')

L1 = ttk.Label(T5, text = '1')
L1.grid(row = 1, column = 1, padx = 10)
L2 = ttk.Label(T5, text = '1')
L2.grid(row = 1, column = 2, padx = 10)
R1 = ttk.Checkbutton(T5, variable = ORVar1)
R1.grid(row = 1, column = 3)
L3 = ttk.Label(T5, text = '1')
L3.grid(row = 2, column = 1, padx = 10)
L4 = ttk.Label(T5, text = '0')
L4.grid(row = 2, column = 2, padx = 10)
R2 = ttk.Checkbutton(T5, variable = ORVar2)
R2.grid(row = 2, column = 3)
L5 = ttk.Label(T5, text = '0')
L5.grid(row = 3, column = 1, padx = 10)
L6 = ttk.Label(T5, text = '1')
L6.grid(row = 3, column = 2, padx = 10)
R3 = ttk.Checkbutton(T5, variable = ORVar3)
R3.grid(row = 3, column = 3)
L7 = ttk.Label(T5, text = '1')
L7.grid(row = 4, column = 1, padx = 10)
L8 = ttk.Label(T5, text = '1')
L8.grid(row = 4, column = 2, padx = 10)
R4 = ttk.Checkbutton(T5, variable = ORVar4)
R4.grid(row = 4, column = 3)
B1 = ttk.Button(T5, text = 'Submit')
B1.grid(row = 1, column = 5, rowspan = 4)
P1 = Label(T5, image = Photo5)
P1.grid(row = 5, column = 2, rowspan = 4, columnspan = 4)
R5 = ttk.Checkbutton(T5, variable = ORVar5)
R5.grid(row = 5, column = 1, rowspan = 2)
R6 = ttk.Checkbutton(T5, variable = ORVar6)
R6.grid(row = 7, column = 1, rowspan = 2)
L9 = ttk.Label(T5, text = '0')
L9.grid(row = 5, column = 7, rowspan = 4)

# OR TAB
# XNOR TAB

XNORVar1 = IntVar(value = 0)
XNORVar2 = IntVar(value = 0)
XNORVar3 = IntVar(value = 0)
XNORVar4 = IntVar(value = 0)
XNORVar5 = IntVar(value = 0)
XNORVar6 = IntVar(value = 0)

Photo6 = PhotoImage(file = 'XNOR.gif')

L1 = ttk.Label(T6, text = '1')
L1.grid(row = 1, column = 1, padx = 10)
L2 = ttk.Label(T6, text = '1')
L2.grid(row = 1, column = 2, padx = 10)
R1 = ttk.Checkbutton(T6, variable = XNORVar1)
R1.grid(row = 1, column = 3)
L3 = ttk.Label(T6, text = '1')
L3.grid(row = 2, column = 1, padx = 10)
L4 = ttk.Label(T6, text = '0')
L4.grid(row = 2, column = 2, padx = 10)
R2 = ttk.Checkbutton(T6, variable = XNORVar2)
R2.grid(row = 2, column = 3)
L5 = ttk.Label(T6, text = '0')
L5.grid(row = 3, column = 1, padx = 10)
L6 = ttk.Label(T6, text = '1')
L6.grid(row = 3, column = 2, padx = 10)
R3 = ttk.Checkbutton(T6, variable = XNORVar3)
R3.grid(row = 3, column = 3)
L7 = ttk.Label(T6, text = '1')
L7.grid(row = 4, column = 1, padx = 10)
L8 = ttk.Label(T6, text = '1')
L8.grid(row = 4, column = 2, padx = 10)
R4 = ttk.Checkbutton(T6, variable = XNORVar4)
R4.grid(row = 4, column = 3)
B1 = ttk.Button(T6, text = 'Submit')
B1.grid(row = 1, column = 5, rowspan = 4)
P1 = Label(T6, image = Photo6)
P1.grid(row = 5, column = 2, rowspan = 4, columnspan = 4)
R5 = ttk.Checkbutton(T6, variable = XNORVar5)
R5.grid(row = 5, column = 1, rowspan = 2)
R6 = ttk.Checkbutton(T6, variable = XNORVar6)
R6.grid(row = 7, column = 1, rowspan = 2)
L9 = ttk.Label(T6, text = '0')
L9.grid(row = 5, column = 7, rowspan = 4)

# XNOR TAB
# XOR TAB

XORVar1 = IntVar(value = 0)
XORVar2 = IntVar(value = 0)
XORVar3 = IntVar(value = 0)
XORVar4 = IntVar(value = 0)
XORVar5 = IntVar(value = 0)
XORVar6 = IntVar(value = 0)

Photo7 = PhotoImage(file = 'XOR.gif')

L1 = ttk.Label(T7, text = '1')
L1.grid(row = 1, column = 1, padx = 10)
L2 = ttk.Label(T7, text = '1')
L2.grid(row = 1, column = 2, padx = 10)
R1 = ttk.Checkbutton(T7, variable = XORVar1)
R1.grid(row = 1, column = 3)
L3 = ttk.Label(T7, text = '1')
L3.grid(row = 2, column = 1, padx = 10)
L4 = ttk.Label(T7, text = '0')
L4.grid(row = 2, column = 2, padx = 10)
R2 = ttk.Checkbutton(T7, variable = XORVar2)
R2.grid(row = 2, column = 3)
L5 = ttk.Label(T7, text = '0')
L5.grid(row = 3, column = 1, padx = 10)
L6 = ttk.Label(T7, text = '1')
L6.grid(row = 3, column = 2, padx = 10)
R3 = ttk.Checkbutton(T7, variable = XORVar3)
R3.grid(row = 3, column = 3)
L7 = ttk.Label(T7, text = '1')
L7.grid(row = 4, column = 1, padx = 10)
L8 = ttk.Label(T7, text = '1')
L8.grid(row = 4, column = 2, padx = 10)
R4 = ttk.Checkbutton(T7, variable = XORVar4)
R4.grid(row = 4, column = 3)
B1 = ttk.Button(T7, text = 'Submit')
B1.grid(row = 1, column = 5, rowspan = 4)
P1 = Label(T7, image = Photo7)
P1.grid(row = 5, column = 2, rowspan = 4, columnspan = 4)
R5 = ttk.Checkbutton(T7, variable = XORVar5)
R5.grid(row = 5, column = 1, rowspan = 2)
R6 = ttk.Checkbutton(T7, variable = XORVar6)
R6.grid(row = 7, column = 1, rowspan = 2)
L9 = ttk.Label(T7, text = '0')
L9.grid(row = 5, column = 7, rowspan = 4)

# XOR TAB

NB.add(T1, text = 'AND')
NB.add(T2, text = 'NAND')
NB.add(T3, text = 'NOR')
NB.add(T4, text = 'NOT')
NB.add(T5, text = 'OR')
NB.add(T6, text = 'XNOR')
NB.add(T7, text = 'XOR')
NB.pack(fill = BOTH)

while True:
        if ANDVar5.get() == 1 and ANDVar6.get() == 1:
            L9.configure(text = '1')
        else:
            L9.configure(text = '0')
        window.update()

window.mainloop()
